# Generated by Django 5.2.14 on 2026-05-06 14:12

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('razao_social', models.CharField(max_length=180)),
                ('nome_fantasia', models.CharField(blank=True, max_length=180)),
                ('cnpj', models.CharField(blank=True, max_length=18, null=True, unique=True)),
                ('status', models.CharField(choices=[('ativa', 'Ativa'), ('inativa', 'Inativa'), ('suspensa', 'Suspensa')], default='ativa', max_length=20)),
                ('timezone', models.CharField(default='America/Cuiaba', max_length=64)),
                ('configuracoes', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['razao_social'],
            },
        ),
        migrations.CreateModel(
            name='Modulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('codigo', models.SlugField(max_length=60, unique=True)),
                ('nome', models.CharField(max_length=120)),
                ('descricao', models.TextField(blank=True)),
                ('ativo', models.BooleanField(default=True)),
                ('schema_configuracao', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('telefone', models.CharField(blank=True, max_length=30)),
                ('cargo', models.CharField(blank=True, max_length=80)),
                ('mfa_habilitado', models.BooleanField(default=False)),
                ('precisa_trocar_senha', models.BooleanField(default=False)),
                ('ultimo_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='usuarios', to='core.empresa')),
            ],
            options={
                'ordering': ['username'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Notificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('canal', models.CharField(choices=[('sistema', 'Sistema'), ('email', 'E-mail'), ('whatsapp', 'WhatsApp'), ('sms', 'SMS'), ('push', 'Push')], max_length=20)),
                ('titulo', models.CharField(max_length=160)),
                ('mensagem', models.TextField()),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('enviada', 'Enviada'), ('falhou', 'Falhou'), ('lida', 'Lida')], default='pendente', max_length=20)),
                ('enviado_em', models.DateTimeField(blank=True, null=True)),
                ('lido_em', models.DateTimeField(blank=True, null=True)),
                ('metadados', models.JSONField(blank=True, default=dict)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificacoes', to='core.empresa')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notificacoes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(max_length=80)),
                ('descricao', models.TextField(blank=True)),
                ('sistema', models.BooleanField(default=False)),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='perfis', to='core.empresa')),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Permissao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('codigo', models.SlugField(max_length=120, unique=True)),
                ('tela', models.CharField(max_length=80)),
                ('acao', models.CharField(max_length=60)),
                ('descricao', models.TextField(blank=True)),
                ('sensivel', models.BooleanField(default=False)),
                ('modulo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='permissoes', to='core.modulo')),
            ],
            options={
                'ordering': ['modulo__codigo', 'tela', 'acao'],
            },
        ),
        migrations.CreateModel(
            name='PerfilPermissao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_permissoes', to='core.perfil')),
                ('permissao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissao_perfis', to='core.permissao')),
            ],
        ),
        migrations.CreateModel(
            name='UsuarioPerfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_usuarios', to='core.perfil')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuario_perfis', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EventLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('tipo_evento', models.CharField(choices=[('criacao', 'Criacao'), ('alteracao', 'Alteracao'), ('exclusao_logica', 'Exclusao logica'), ('baixa', 'Baixa'), ('aprovacao', 'Aprovacao'), ('reprovacao', 'Reprovacao'), ('exportacao', 'Exportacao'), ('acesso_sensivel', 'Acesso sensivel'), ('alerta_sistema', 'Alerta do sistema'), ('alerta_ia', 'Alerta de IA'), ('integracao', 'Integracao')], max_length=40)),
                ('modulo', models.CharField(max_length=80)),
                ('tela', models.CharField(blank=True, max_length=80)),
                ('acao', models.CharField(max_length=80)),
                ('registro_modelo', models.CharField(blank=True, max_length=120)),
                ('registro_id', models.CharField(blank=True, max_length=80)),
                ('valor_anterior', models.JSONField(blank=True, null=True)),
                ('valor_novo', models.JSONField(blank=True, null=True)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('dispositivo', models.CharField(blank=True, max_length=255)),
                ('origem', models.CharField(default='sistema', max_length=80)),
                ('justificativa', models.TextField(blank=True)),
                ('nivel_risco', models.CharField(choices=[('baixo', 'Baixo'), ('medio', 'Medio'), ('alto', 'Alto'), ('critico', 'Critico')], default='baixo', max_length=20)),
                ('metadados', models.JSONField(blank=True, default=dict)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos', to='core.empresa')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-criado_em'],
                'indexes': [models.Index(fields=['empresa', 'criado_em'], name='core_eventl_empresa_7f35db_idx'), models.Index(fields=['tipo_evento', 'nivel_risco'], name='core_eventl_tipo_ev_82dbee_idx'), models.Index(fields=['modulo', 'acao'], name='core_eventl_modulo_0a9ed4_idx'), models.Index(fields=['registro_modelo', 'registro_id'], name='core_eventl_registr_a60e00_idx')],
            },
        ),
        migrations.CreateModel(
            name='EmpresaModulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('ativo', models.BooleanField(default=True)),
                ('instalado_em', models.DateTimeField(auto_now_add=True)),
                ('configuracoes', models.JSONField(blank=True, default=dict)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modulos', to='core.empresa')),
                ('modulo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='empresas', to='core.modulo')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('empresa', 'modulo'), name='uniq_empresa_modulo')],
            },
        ),
        migrations.AddConstraint(
            model_name='perfil',
            constraint=models.UniqueConstraint(fields=('empresa', 'nome'), name='uniq_perfil_empresa_nome'),
        ),
        migrations.AddConstraint(
            model_name='perfilpermissao',
            constraint=models.UniqueConstraint(fields=('perfil', 'permissao'), name='uniq_perfil_permissao'),
        ),
        migrations.AddConstraint(
            model_name='usuarioperfil',
            constraint=models.UniqueConstraint(fields=('usuario', 'perfil'), name='uniq_usuario_perfil'),
        ),
    ]
