# Generated by Django 5.2.14 on 2026-05-06 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventlog',
            name='hash_anterior',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='eventlog',
            name='hash_evento',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.CreateModel(
            name='LoginAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('falhas', models.PositiveIntegerField(default=0)),
                ('bloqueado_ate', models.DateTimeField(blank=True, null=True)),
                ('ultimo_evento', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['username', 'ip', 'bloqueado_ate'], name='core_logina_usernam_a7f1e5_idx')],
                'constraints': [models.UniqueConstraint(fields=('username', 'ip'), name='uniq_login_attempt_username_ip')],
            },
        ),
    ]
