# Generated by Django 5.2.14 on 2026-06-01 19:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_eventlog_hash_anterior_eventlog_hash_evento_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricoSenha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('hash_senha', models.CharField(max_length=255)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico_senhas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Historico de Senha',
                'verbose_name_plural': 'Historico de Senhas',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='MFASecret',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('secret', models.CharField(max_length=64)),
                ('backup_codes', models.JSONField(default=list)),
                ('ativado_em', models.DateTimeField(blank=True, null=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mfa_secret', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'MFA Secret',
                'verbose_name_plural': 'MFA Secrets',
            },
        ),
    ]
