# Generated by Django 5.2.14 on 2026-06-01 19:41

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0003_historicosenha_mfasecret'),
        ('financeiro', '0004_alcadaaprovacao_aplicacaofinanceira_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CentroResultadoContabil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('codigo', models.CharField(max_length=40)),
                ('nome', models.CharField(max_length=120)),
                ('ativo', models.BooleanField(default=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='centros_resultado_contabil', to='core.empresa')),
                ('pai', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='filhos', to='contabil.centroresultadocontabil')),
            ],
            options={
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='CompetenciaContabil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('ano', models.PositiveSmallIntegerField()),
                ('mes', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('status', models.CharField(choices=[('aberto', 'Aberto'), ('em_fechamento', 'Em Fechamento'), ('fechado', 'Fechado'), ('reaberto', 'Reaberto')], default='aberto', max_length=20)),
                ('fechado_em', models.DateTimeField(blank=True, null=True)),
                ('reaberto_em', models.DateTimeField(blank=True, null=True)),
                ('justificativa_reabertura', models.TextField(blank=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competencias_contabeis', to='core.empresa')),
                ('fechado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='competencias_fechadas', to=settings.AUTH_USER_MODEL)),
                ('reaberto_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='competencias_reabertas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-ano', '-mes'],
            },
        ),
        migrations.CreateModel(
            name='ContaContabil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('codigo', models.CharField(max_length=40)),
                ('nome', models.CharField(max_length=120)),
                ('natureza', models.CharField(choices=[('ativo', 'Ativo'), ('passivo', 'Passivo'), ('patrimonio_liquido', 'Patrimônio Líquido'), ('receita', 'Receita'), ('despesa', 'Despesa'), ('custo', 'Custo'), ('resultado', 'Resultado')], max_length=30)),
                ('tipo_saldo', models.CharField(choices=[('devedora', 'Devedora'), ('credora', 'Credora')], max_length=10)),
                ('aceita_lancamento', models.BooleanField(default=True, help_text='Contas sintéticas não aceitam lançamentos diretos.')),
                ('ativo', models.BooleanField(default=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contas_contabeis', to='core.empresa')),
                ('pai', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='filhos', to='contabil.contacontabil')),
                ('plano_conta_financeiro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contas_contabeis', to='financeiro.planoconta')),
            ],
            options={
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='HistoricoPadrao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('codigo', models.CharField(max_length=20)),
                ('descricao', models.CharField(max_length=200)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historicos_padrao', to='core.empresa')),
            ],
            options={
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='LancamentoContabil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('numero', models.PositiveIntegerField(editable=False, help_text='Número sequencial por empresa, gerado automaticamente.')),
                ('data_lancamento', models.DateField()),
                ('data_competencia', models.DateField()),
                ('tipo', models.CharField(choices=[('manual', 'Manual'), ('automatico', 'Automático'), ('estorno', 'Estorno'), ('ajuste', 'Ajuste')], default='manual', max_length=20)),
                ('historico', models.TextField()),
                ('origem_modelo', models.CharField(blank=True, help_text='Ex: financeiro.ContaPagar', max_length=120)),
                ('origem_id', models.CharField(blank=True, max_length=80)),
                ('estornado', models.BooleanField(default=False)),
                ('excluido_logicamente', models.BooleanField(default=False)),
                ('justificativa_exclusao', models.TextField(blank=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lancamentos_contabeis', to='core.empresa')),
                ('historico_padrao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lancamentos', to='contabil.historicopadrao')),
                ('lancamento_original', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estornos', to='contabil.lancamentocontabil')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lancamentos_contabeis', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-data_lancamento', '-numero'],
            },
        ),
        migrations.CreateModel(
            name='PartidaContabil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('tipo_partida', models.CharField(choices=[('debito', 'Débito'), ('credito', 'Crédito')], max_length=10)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=14)),
                ('historico_complementar', models.CharField(blank=True, max_length=200)),
                ('centro_resultado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='partidas', to='contabil.centroresultadocontabil')),
                ('conta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='partidas', to='contabil.contacontabil')),
                ('lancamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partidas', to='contabil.lancamentocontabil')),
            ],
            options={
                'ordering': ['tipo_partida', 'conta__codigo'],
            },
        ),
        migrations.AddConstraint(
            model_name='centroresultadocontabil',
            constraint=models.UniqueConstraint(fields=('empresa', 'codigo'), name='uniq_centro_resultado_contabil_empresa_codigo'),
        ),
        migrations.AddConstraint(
            model_name='competenciacontabil',
            constraint=models.UniqueConstraint(fields=('empresa', 'ano', 'mes'), name='uniq_competencia_contabil_empresa_ano_mes'),
        ),
        migrations.AddIndex(
            model_name='contacontabil',
            index=models.Index(fields=['empresa', 'natureza'], name='contabil_co_empresa_81e92b_idx'),
        ),
        migrations.AddIndex(
            model_name='contacontabil',
            index=models.Index(fields=['empresa', 'ativo'], name='contabil_co_empresa_9a8123_idx'),
        ),
        migrations.AddConstraint(
            model_name='contacontabil',
            constraint=models.UniqueConstraint(fields=('empresa', 'codigo'), name='uniq_conta_contabil_empresa_codigo'),
        ),
        migrations.AddConstraint(
            model_name='historicopadrao',
            constraint=models.UniqueConstraint(fields=('empresa', 'codigo'), name='uniq_historico_padrao_empresa_codigo'),
        ),
        migrations.AddIndex(
            model_name='lancamentocontabil',
            index=models.Index(fields=['empresa', 'data_lancamento'], name='contabil_la_empresa_184474_idx'),
        ),
        migrations.AddIndex(
            model_name='lancamentocontabil',
            index=models.Index(fields=['empresa', 'data_competencia'], name='contabil_la_empresa_7cc6c4_idx'),
        ),
        migrations.AddIndex(
            model_name='lancamentocontabil',
            index=models.Index(fields=['origem_modelo', 'origem_id'], name='contabil_la_origem__9bc2fc_idx'),
        ),
        migrations.AddIndex(
            model_name='partidacontabil',
            index=models.Index(fields=['lancamento', 'tipo_partida'], name='contabil_pa_lancame_14a0d7_idx'),
        ),
        migrations.AddIndex(
            model_name='partidacontabil',
            index=models.Index(fields=['conta'], name='contabil_pa_conta_i_36d8fa_idx'),
        ),
    ]
