# Generated by Django 5.2.14 on 2026-06-01 19:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0003_historicosenha_mfasecret'),
        ('financeiro', '0004_alcadaaprovacao_aplicacaofinanceira_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoFiscalEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('regime_tributario', models.CharField(choices=[('simples_nacional', 'Simples Nacional'), ('lucro_presumido', 'Lucro Presumido'), ('lucro_real', 'Lucro Real'), ('mei', 'MEI')], default='simples_nacional', max_length=30)),
                ('inscricao_estadual', models.CharField(blank=True, max_length=30)),
                ('inscricao_municipal', models.CharField(blank=True, max_length=30)),
                ('cnae_principal', models.CharField(blank=True, max_length=10)),
                ('aliquota_iss', models.DecimalField(decimal_places=2, default=5.0, max_digits=5)),
                ('aliquota_pis', models.DecimalField(decimal_places=2, default=0.65, max_digits=5)),
                ('aliquota_cofins', models.DecimalField(decimal_places=2, default=3.0, max_digits=5)),
                ('aliquota_irpj', models.DecimalField(decimal_places=2, default=15.0, max_digits=5)),
                ('aliquota_csll', models.DecimalField(decimal_places=2, default=9.0, max_digits=5)),
                ('retencao_inss', models.BooleanField(default=False)),
                ('aliquota_inss', models.DecimalField(decimal_places=2, default=11.0, max_digits=5)),
                ('configuracoes_extras', models.JSONField(default=dict)),
                ('empresa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='configuracao_fiscal', to='core.empresa')),
            ],
            options={
                'verbose_name': 'Configuracao Fiscal da Empresa',
                'verbose_name_plural': 'Configuracoes Fiscais das Empresas',
            },
        ),
        migrations.CreateModel(
            name='NotaFiscal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('tipo', models.CharField(choices=[('nfe', 'NF-e'), ('nfse', 'NFS-e'), ('nfce', 'NFC-e'), ('cte', 'CT-e')], max_length=10)),
                ('numero', models.CharField(blank=True, max_length=20)),
                ('serie', models.CharField(blank=True, max_length=5)),
                ('chave_acesso', models.CharField(blank=True, max_length=44)),
                ('protocolo', models.CharField(blank=True, max_length=60)),
                ('data_emissao', models.DateField()),
                ('data_competencia', models.DateField(blank=True, null=True)),
                ('valor_produtos', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('valor_servicos', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('valor_desconto', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('valor_iss', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('valor_pis', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('valor_cofins', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('valor_irrf', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('valor_csll', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('valor_inss', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=14)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('emitida', 'Emitida'), ('autorizada', 'Autorizada'), ('cancelada', 'Cancelada'), ('rejeitada', 'Rejeitada'), ('inutilizada', 'Inutilizada')], default='pendente', max_length=20)),
                ('xml_nota', models.TextField(blank=True)),
                ('pdf_danfe', models.FileField(blank=True, null=True, upload_to='fiscal/danfe/')),
                ('observacao', models.TextField(blank=True)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notas_fiscais', to='financeiro.cliente')),
                ('conta_pagar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notas_fiscais', to='financeiro.contapagar')),
                ('conta_receber', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notas_fiscais', to='financeiro.contareceber')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas_fiscais', to='core.empresa')),
                ('fornecedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notas_fiscais', to='financeiro.fornecedor')),
            ],
            options={
                'verbose_name': 'Nota Fiscal',
                'verbose_name_plural': 'Notas Fiscais',
                'ordering': ['-data_emissao'],
            },
        ),
        migrations.CreateModel(
            name='ItemNotaFiscal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('descricao', models.CharField(max_length=200)),
                ('quantidade', models.DecimalField(decimal_places=3, max_digits=10)),
                ('valor_unitario', models.DecimalField(decimal_places=2, max_digits=14)),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=14)),
                ('codigo_servico_municipal', models.CharField(blank=True, max_length=20)),
                ('aliquota_iss', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('valor_iss', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('servico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itens_nota_fiscal', to='financeiro.servico')),
                ('nota_fiscal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='fiscal.notafiscal')),
            ],
            options={
                'verbose_name': 'Item de Nota Fiscal',
                'verbose_name_plural': 'Itens de Nota Fiscal',
            },
        ),
        migrations.CreateModel(
            name='EventoFiscal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('tipo_evento', models.CharField(choices=[('emissao', 'Emissao'), ('autorizacao', 'Autorizacao'), ('cancelamento', 'Cancelamento'), ('inutilizacao', 'Inutilizacao'), ('consulta', 'Consulta'), ('rejeicao', 'Rejeicao')], max_length=20)),
                ('descricao', models.CharField(max_length=200)),
                ('codigo_retorno', models.CharField(blank=True, max_length=10)),
                ('mensagem_retorno', models.TextField(blank=True)),
                ('xml_evento', models.TextField(blank=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos_fiscais', to=settings.AUTH_USER_MODEL)),
                ('nota_fiscal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='fiscal.notafiscal')),
            ],
            options={
                'verbose_name': 'Evento Fiscal',
                'verbose_name_plural': 'Eventos Fiscais',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='ObrigacaoFiscal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('descricao', models.CharField(max_length=160)),
                ('tipo', models.CharField(choices=[('declaracao', 'Declaracao'), ('pagamento', 'Pagamento'), ('entrega', 'Entrega')], max_length=20)),
                ('competencia_ano', models.PositiveSmallIntegerField()),
                ('competencia_mes', models.PositiveSmallIntegerField()),
                ('data_vencimento', models.DateField()),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('cumprida', 'Cumprida'), ('atrasada', 'Atrasada'), ('dispensada', 'Dispensada')], default='pendente', max_length=20)),
                ('observacao', models.TextField(blank=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='obrigacoes_fiscais', to='core.empresa')),
            ],
            options={
                'verbose_name': 'Obrigacao Fiscal',
                'verbose_name_plural': 'Obrigacoes Fiscais',
                'ordering': ['data_vencimento'],
            },
        ),
        migrations.CreateModel(
            name='ConfiguracaoImpostoPorServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('tipo_imposto', models.CharField(choices=[('iss', 'ISS'), ('pis', 'PIS'), ('cofins', 'COFINS'), ('irpj', 'IRPJ'), ('csll', 'CSLL'), ('inss_retido', 'INSS Retido'), ('icms', 'ICMS'), ('ipi', 'IPI')], max_length=20)),
                ('aliquota', models.DecimalField(decimal_places=2, max_digits=5)),
                ('retencao', models.BooleanField(default=False)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configuracoes_imposto_servico', to='core.empresa')),
                ('servico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configuracoes_imposto', to='financeiro.servico')),
            ],
            options={
                'verbose_name': 'Configuracao de Imposto por Servico',
                'verbose_name_plural': 'Configuracoes de Imposto por Servico',
                'constraints': [models.UniqueConstraint(fields=('empresa', 'servico', 'tipo_imposto'), name='uniq_config_imposto_servico')],
            },
        ),
        migrations.CreateModel(
            name='ImpostoApurado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('ano', models.PositiveSmallIntegerField()),
                ('mes', models.PositiveSmallIntegerField()),
                ('tipo_imposto', models.CharField(choices=[('iss', 'ISS'), ('pis', 'PIS'), ('cofins', 'COFINS'), ('irpj', 'IRPJ'), ('csll', 'CSLL'), ('inss_retido', 'INSS Retido'), ('icms', 'ICMS'), ('ipi', 'IPI')], max_length=20)),
                ('base_calculo', models.DecimalField(decimal_places=2, max_digits=14)),
                ('aliquota', models.DecimalField(decimal_places=2, max_digits=5)),
                ('valor_apurado', models.DecimalField(decimal_places=2, max_digits=14)),
                ('valor_retido', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('valor_a_pagar', models.DecimalField(decimal_places=2, max_digits=14)),
                ('data_vencimento', models.DateField(blank=True, null=True)),
                ('conta_pagar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='impostos_apurados', to='financeiro.contapagar')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='impostos_apurados', to='core.empresa')),
            ],
            options={
                'verbose_name': 'Imposto Apurado',
                'verbose_name_plural': 'Impostos Apurados',
                'ordering': ['-ano', '-mes', 'tipo_imposto'],
                'constraints': [models.UniqueConstraint(fields=('empresa', 'ano', 'mes', 'tipo_imposto'), name='uniq_imposto_apurado_periodo')],
            },
        ),
        migrations.AddIndex(
            model_name='notafiscal',
            index=models.Index(fields=['empresa', 'status', 'data_emissao'], name='fiscal_nota_empresa_adf642_idx'),
        ),
    ]
