# Generated by Django 5.2.14 on 2026-05-06 14:12

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CentroCusto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('codigo', models.CharField(max_length=40)),
                ('nome', models.CharField(max_length=120)),
                ('ativo', models.BooleanField(default=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='centros_custo', to='core.empresa')),
                ('pai', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='filhos', to='financeiro.centrocusto')),
            ],
            options={
                'ordering': ['codigo', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(max_length=180)),
                ('tipo_pessoa', models.CharField(choices=[('fisica', 'Fisica'), ('juridica', 'Juridica')], default='juridica', max_length=20)),
                ('documento', models.CharField(blank=True, max_length=18)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('telefone', models.CharField(blank=True, max_length=30)),
                ('ativo', models.BooleanField(default=True)),
                ('metadados', models.JSONField(blank=True, default=dict)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clientes', to='core.empresa')),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='ContaBancaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('banco', models.CharField(max_length=80)),
                ('agencia', models.CharField(blank=True, max_length=20)),
                ('numero', models.CharField(max_length=40)),
                ('descricao', models.CharField(blank=True, max_length=120)),
                ('saldo_inicial', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('ativa', models.BooleanField(default=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contas_bancarias', to='core.empresa')),
            ],
            options={
                'ordering': ['banco', 'numero'],
            },
        ),
        migrations.CreateModel(
            name='ContaPagar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('descricao', models.CharField(max_length=180)),
                ('data_emissao', models.DateField()),
                ('data_vencimento', models.DateField()),
                ('valor_original', models.DecimalField(decimal_places=2, max_digits=14)),
                ('desconto', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('juros', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('multa', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('acrescimo', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('observacao', models.TextField(blank=True)),
                ('excluido_logicamente', models.BooleanField(default=False)),
                ('excluido_em', models.DateTimeField(blank=True, null=True)),
                ('numero_documento', models.CharField(blank=True, max_length=80)),
                ('nota_fiscal', models.CharField(blank=True, max_length=80)),
                ('valor_pago', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('forma_pagamento', models.CharField(blank=True, max_length=80)),
                ('status', models.CharField(choices=[('aberto', 'Aberto'), ('a_vencer', 'A vencer'), ('vencido', 'Vencido'), ('pago', 'Pago'), ('pago_parcial', 'Pago parcial'), ('cancelado', 'Cancelado'), ('em_aprovacao', 'Em aprovacao'), ('reprovado', 'Reprovado'), ('agendado', 'Agendado')], default='aberto', max_length=30)),
                ('data_baixa', models.DateTimeField(blank=True, null=True)),
                ('comprovante', models.FileField(blank=True, null=True, upload_to='comprovantes/pagar/')),
                ('baixado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contas_pagar_baixadas', to=settings.AUTH_USER_MODEL)),
                ('centro_custo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='financeiro.centrocusto')),
                ('conta_bancaria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='financeiro.contabancaria')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.empresa')),
                ('excluido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_exclusoes', to=settings.AUTH_USER_MODEL)),
                ('responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_responsavel', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['data_vencimento', 'fornecedor__nome'],
            },
        ),
        migrations.CreateModel(
            name='AprovacaoPagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('aprovado', 'Aprovado'), ('reprovado', 'Reprovado'), ('cancelado', 'Cancelado')], default='pendente', max_length=20)),
                ('justificativa', models.TextField(blank=True)),
                ('decidido_em', models.DateTimeField(blank=True, null=True)),
                ('aprovador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aprovacoes_realizadas', to=settings.AUTH_USER_MODEL)),
                ('solicitante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aprovacoes_solicitadas', to=settings.AUTH_USER_MODEL)),
                ('conta_pagar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aprovacoes', to='financeiro.contapagar')),
            ],
            options={
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(max_length=180)),
                ('tipo_pessoa', models.CharField(choices=[('fisica', 'Fisica'), ('juridica', 'Juridica')], default='juridica', max_length=20)),
                ('documento', models.CharField(blank=True, max_length=18)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('telefone', models.CharField(blank=True, max_length=30)),
                ('ativo', models.BooleanField(default=True)),
                ('metadados', models.JSONField(blank=True, default=dict)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fornecedores', to='core.empresa')),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.AddField(
            model_name='contapagar',
            name='fornecedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contas_pagar', to='financeiro.fornecedor'),
        ),
        migrations.CreateModel(
            name='MovimentacaoFinanceira',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('tipo', models.CharField(choices=[('entrada', 'Entrada'), ('saida', 'Saida')], max_length=20)),
                ('descricao', models.CharField(max_length=180)),
                ('data_movimento', models.DateField()),
                ('data_competencia', models.DateField(blank=True, null=True)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=14)),
                ('origem_modelo', models.CharField(blank=True, max_length=120)),
                ('origem_id', models.CharField(blank=True, max_length=80)),
                ('conciliado', models.BooleanField(default=False)),
                ('centro_custo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='financeiro.centrocusto')),
                ('conta_bancaria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimentacoes', to='financeiro.contabancaria')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimentacoes_financeiras', to='core.empresa')),
            ],
            options={
                'ordering': ['-data_movimento', '-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='ConciliacaoBancaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('data_movimento', models.DateField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=14)),
                ('historico', models.TextField()),
                ('documento', models.CharField(blank=True, max_length=80)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('sugerida', 'Sugerida'), ('conciliada', 'Conciliada'), ('divergente', 'Divergente'), ('duplicada', 'Duplicada')], default='pendente', max_length=30)),
                ('metadados', models.JSONField(blank=True, default=dict)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conciliacoes_bancarias', to='core.empresa')),
                ('conta_bancaria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='conciliacoes', to='financeiro.contabancaria')),
                ('movimentacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conciliacoes', to='financeiro.movimentacaofinanceira')),
            ],
            options={
                'ordering': ['-data_movimento', '-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='PlanoConta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('codigo', models.CharField(max_length=40)),
                ('nome', models.CharField(max_length=120)),
                ('tipo', models.CharField(choices=[('receita', 'Receita'), ('despesa', 'Despesa'), ('custo', 'Custo'), ('investimento', 'Investimento'), ('imposto', 'Imposto'), ('taxa', 'Taxa'), ('comissao', 'Comissao'), ('repasse', 'Repasse'), ('financiamento', 'Financiamento'), ('emprestimo', 'Emprestimo')], max_length=30)),
                ('vincula_dre', models.BooleanField(default=True)),
                ('vincula_fluxo_caixa', models.BooleanField(default=True)),
                ('ativo', models.BooleanField(default=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plano_contas', to='core.empresa')),
                ('pai', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='filhos', to='financeiro.planoconta')),
            ],
            options={
                'ordering': ['codigo', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='Orcamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('ano', models.PositiveSmallIntegerField()),
                ('mes', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('valor_previsto', models.DecimalField(decimal_places=2, max_digits=14)),
                ('valor_realizado', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('centro_custo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='financeiro.centrocusto')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orcamentos', to='core.empresa')),
                ('plano_conta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='financeiro.planoconta')),
            ],
            options={
                'ordering': ['ano', 'mes'],
            },
        ),
        migrations.AddField(
            model_name='movimentacaofinanceira',
            name='plano_conta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='financeiro.planoconta'),
        ),
        migrations.CreateModel(
            name='ContaReceber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('descricao', models.CharField(max_length=180)),
                ('data_emissao', models.DateField()),
                ('data_vencimento', models.DateField()),
                ('valor_original', models.DecimalField(decimal_places=2, max_digits=14)),
                ('desconto', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('juros', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('multa', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('acrescimo', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('observacao', models.TextField(blank=True)),
                ('excluido_logicamente', models.BooleanField(default=False)),
                ('excluido_em', models.DateTimeField(blank=True, null=True)),
                ('contrato', models.CharField(blank=True, max_length=80)),
                ('parcela', models.PositiveIntegerField(blank=True, null=True)),
                ('valor_recebido', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('honorarios', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('forma_recebimento', models.CharField(blank=True, max_length=80)),
                ('status', models.CharField(choices=[('aberto', 'Aberto'), ('a_vencer', 'A vencer'), ('vencido', 'Vencido'), ('recebido', 'Recebido'), ('recebido_parcial', 'Recebido parcial'), ('cancelado', 'Cancelado'), ('renegociado', 'Renegociado'), ('em_cobranca', 'Em cobranca'), ('judicial', 'Judicial'), ('protestado', 'Protestado')], default='aberto', max_length=30)),
                ('data_recebimento', models.DateTimeField(blank=True, null=True)),
                ('centro_custo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='financeiro.centrocusto')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contas_receber', to='financeiro.cliente')),
                ('conta_bancaria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='financeiro.contabancaria')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.empresa')),
                ('excluido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_exclusoes', to=settings.AUTH_USER_MODEL)),
                ('recebido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contas_receber_recebidas', to=settings.AUTH_USER_MODEL)),
                ('responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_responsavel', to=settings.AUTH_USER_MODEL)),
                ('plano_conta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='financeiro.planoconta')),
            ],
            options={
                'ordering': ['data_vencimento', 'cliente__nome'],
            },
        ),
        migrations.AddField(
            model_name='contapagar',
            name='plano_conta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='financeiro.planoconta'),
        ),
        migrations.AddConstraint(
            model_name='centrocusto',
            constraint=models.UniqueConstraint(fields=('empresa', 'codigo'), name='uniq_centro_custo_empresa_codigo'),
        ),
        migrations.AddIndex(
            model_name='cliente',
            index=models.Index(fields=['empresa', 'documento'], name='financeiro__empresa_c86f3c_idx'),
        ),
        migrations.AddIndex(
            model_name='fornecedor',
            index=models.Index(fields=['empresa', 'documento'], name='financeiro__empresa_54e2c9_idx'),
        ),
        migrations.AddIndex(
            model_name='conciliacaobancaria',
            index=models.Index(fields=['empresa', 'status', 'data_movimento'], name='financeiro__empresa_9688fe_idx'),
        ),
        migrations.AddConstraint(
            model_name='planoconta',
            constraint=models.UniqueConstraint(fields=('empresa', 'codigo'), name='uniq_plano_conta_empresa_codigo'),
        ),
        migrations.AddConstraint(
            model_name='orcamento',
            constraint=models.UniqueConstraint(fields=('empresa', 'ano', 'mes', 'centro_custo', 'plano_conta'), name='uniq_orcamento_dimensoes'),
        ),
        migrations.AddIndex(
            model_name='movimentacaofinanceira',
            index=models.Index(fields=['empresa', 'tipo', 'data_movimento'], name='financeiro__empresa_e828e2_idx'),
        ),
        migrations.AddIndex(
            model_name='movimentacaofinanceira',
            index=models.Index(fields=['origem_modelo', 'origem_id'], name='financeiro__origem__9d43b9_idx'),
        ),
        migrations.AddIndex(
            model_name='contareceber',
            index=models.Index(fields=['empresa', 'status', 'data_vencimento'], name='financeiro__empresa_6de7c2_idx'),
        ),
        migrations.AddIndex(
            model_name='contareceber',
            index=models.Index(fields=['empresa', 'cliente', 'contrato'], name='financeiro__empresa_9776f7_idx'),
        ),
        migrations.AddIndex(
            model_name='contapagar',
            index=models.Index(fields=['empresa', 'status', 'data_vencimento'], name='financeiro__empresa_c2d216_idx'),
        ),
        migrations.AddIndex(
            model_name='contapagar',
            index=models.Index(fields=['empresa', 'fornecedor', 'numero_documento'], name='financeiro__empresa_cebd83_idx'),
        ),
    ]
