# Generated by Django 5.2.14 on 2026-05-06 14:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_eventlog_hash_anterior_eventlog_hash_evento_and_more'),
        ('financeiro', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='contareceber',
            name='conta_original',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='renegociacoes', to='financeiro.contareceber'),
        ),
        migrations.AddField(
            model_name='contareceber',
            name='renegociado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contareceber',
            name='renegociado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contas_receber_renegociadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='AnexoFinanceiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('arquivo', models.FileField(upload_to='anexos/financeiro/')),
                ('nome_original', models.CharField(max_length=180)),
                ('content_type', models.CharField(blank=True, max_length=120)),
                ('tamanho', models.PositiveIntegerField(default=0)),
                ('origem_modelo', models.CharField(max_length=120)),
                ('origem_id', models.CharField(max_length=80)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anexos_financeiros', to='core.empresa')),
                ('enviado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-criado_em'],
                'indexes': [models.Index(fields=['empresa', 'origem_modelo', 'origem_id'], name='financeiro__empresa_604069_idx')],
            },
        ),
        migrations.CreateModel(
            name='RelatorioGerado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('tipo', models.CharField(max_length=80)),
                ('formato', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('processando', 'Processando'), ('pronto', 'Pronto'), ('falhou', 'Falhou')], default='pronto', max_length=20)),
                ('parametros', models.JSONField(blank=True, default=dict)),
                ('arquivo', models.FileField(blank=True, null=True, upload_to='relatorios/')),
                ('erro', models.TextField(blank=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relatorios', to='core.empresa')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-criado_em'],
                'indexes': [models.Index(fields=['empresa', 'tipo', 'formato', 'criado_em'], name='financeiro__empresa_873be6_idx')],
            },
        ),
    ]
