# Generated by Django 5.2.14 on 2026-05-25 23:04

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_eventlog_hash_anterior_eventlog_hash_evento_and_more'),
        ('financeiro', '0002_contareceber_conta_original_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('codigo', models.CharField(blank=True, max_length=40)),
                ('nome', models.CharField(max_length=160)),
                ('descricao', models.TextField(blank=True)),
                ('valor_padrao', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('ativo', models.BooleanField(default=True)),
                ('metadados', models.JSONField(blank=True, default=dict)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicos', to='core.empresa')),
                ('plano_conta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='servicos', to='financeiro.planoconta')),
            ],
            options={
                'ordering': ['nome'],
                'indexes': [models.Index(fields=['empresa', 'nome'], name='financeiro__empresa_c7433f_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('codigo', ''), _negated=True), fields=('empresa', 'codigo'), name='uniq_servico_empresa_codigo')],
            },
        ),
    ]
