# Generated by Django 5.2.14 on 2026-05-06 14:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertaIA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('titulo', models.CharField(max_length=180)),
                ('mensagem', models.TextField()),
                ('nivel_risco', models.CharField(choices=[('baixo', 'Baixo'), ('medio', 'Medio'), ('alto', 'Alto'), ('critico', 'Critico')], default='medio', max_length=20)),
                ('status', models.CharField(choices=[('aberto', 'Aberto'), ('em_analise', 'Em analise'), ('confirmado', 'Confirmado'), ('descartado', 'Descartado'), ('resolvido', 'Resolvido')], default='aberto', max_length=20)),
                ('origem_modelo', models.CharField(blank=True, max_length=120)),
                ('origem_id', models.CharField(blank=True, max_length=80)),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('metadados', models.JSONField(blank=True, default=dict)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertas_ia', to='core.empresa')),
            ],
            options={
                'ordering': ['-criado_em'],
                'indexes': [models.Index(fields=['empresa', 'status', 'nivel_risco'], name='inteligenci_empresa_d5fa14_idx')],
            },
        ),
        migrations.CreateModel(
            name='Anomalia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('tipo', models.CharField(choices=[('pagamento_duplicado', 'Pagamento duplicado'), ('valor_fora_padrao', 'Valor fora do padrao'), ('comportamento_usuario', 'Comportamento de usuario'), ('inadimplencia', 'Inadimplencia'), ('orcamento_estourado', 'Orcamento estourado')], max_length=40)),
                ('descricao', models.TextField()),
                ('nivel_risco', models.CharField(choices=[('baixo', 'Baixo'), ('medio', 'Medio'), ('alto', 'Alto'), ('critico', 'Critico')], default='medio', max_length=20)),
                ('status', models.CharField(choices=[('aberto', 'Aberto'), ('em_analise', 'Em analise'), ('confirmado', 'Confirmado'), ('descartado', 'Descartado'), ('resolvido', 'Resolvido')], default='aberto', max_length=20)),
                ('entidade_modelo', models.CharField(blank=True, max_length=120)),
                ('entidade_id', models.CharField(blank=True, max_length=80)),
                ('evidencia', models.JSONField(blank=True, default=dict)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anomalias', to='core.empresa')),
            ],
            options={
                'ordering': ['-criado_em'],
                'indexes': [models.Index(fields=['empresa', 'tipo', 'status'], name='inteligenci_empresa_ef71cd_idx')],
            },
        ),
        migrations.CreateModel(
            name='PrevisaoIA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(max_length=160)),
                ('data_referencia', models.DateField()),
                ('horizonte_dias', models.PositiveIntegerField()),
                ('metrica', models.CharField(max_length=80)),
                ('valor_previsto', models.DecimalField(decimal_places=2, max_digits=14)),
                ('confianca', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('modelo', models.CharField(default='baseline', max_length=80)),
                ('parametros', models.JSONField(blank=True, default=dict)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='previsoes_ia', to='core.empresa')),
            ],
            options={
                'ordering': ['-data_referencia', 'metrica'],
                'indexes': [models.Index(fields=['empresa', 'metrica', 'data_referencia'], name='inteligenci_empresa_e6bf16_idx')],
            },
        ),
    ]
